// Translations of the existing role labels; this does not update or enrich filing data.
const ROLES = {
  '价值投资 · 沃伦·巴菲特': 'Value investing · Warren Buffett',
  '激进投资 · 比尔·阿克曼': 'Activist investing · Bill Ackman',
  '家族办公室 · 德鲁肯米勒': 'Family office · Druckenmiller',
  '对冲基金 · 戴维·泰珀': 'Hedge fund · David Tepper',
  '宏观对冲 · 瑞·达利欧创立': 'Macro hedge fund · Founded by Ray Dalio',
  '量化对冲 · 吉姆·西蒙斯创立': 'Quantitative hedge fund · Founded by Jim Simons',
  '量化对冲 · 肯·格里芬': 'Quantitative hedge fund · Ken Griffin',
  '价值投资 · 塞思·卡拉曼': 'Value investing · Seth Klarman',
  '激进投资 · 丹尼尔·勒布': 'Activist investing · Daniel Loeb',
  '对冲基金 · 哈尔沃森': 'Hedge fund · Halvorsen',
  '对冲基金 · 蔡斯·科尔曼': 'Hedge fund · Chase Coleman',
  '宏观对冲 · 乔治·索罗斯创立': 'Macro hedge fund · Founded by George Soros',
  '科技对冲 · 菲利普·拉丰': 'Technology hedge fund · Philippe Laffont',
  '多策略对冲 · 史蒂文·科恩': 'Multi-strategy hedge fund · Steven Cohen',
  '激进投资 · 卡尔·伊坎': 'Activist investing · Carl Icahn',
  '激进投资 · 保罗·辛格': 'Activist investing · Paul Singer',
  '对冲基金 · 斯蒂芬·曼德尔': 'Hedge fund · Stephen Mandel',
  '量化对冲 · 奥弗德克与西格尔': 'Quantitative hedge fund · Overdeck and Siegel',
  '量化对冲 · 戴维·E·肖创立': 'Quantitative hedge fund · Founded by David E. Shaw',
  '多策略对冲 · 英格兰德': 'Multi-strategy hedge fund · Englander',
  '激进投资 · 杰弗里·史密斯': 'Activist investing · Jeffrey Smith',
  '激进投资 · 杰弗里·乌本创立': 'Activist investing · Founded by Jeffrey Ubben',
  '主动ETF · 凯瑟琳·伍德': 'Actively managed ETFs · Cathie Wood',
  '不良资产 · 霍华德·马克斯': 'Distressed assets · Howard Marks',
  '对冲基金 · 约翰·保尔森': 'Hedge fund · John Paulson',
  '价值投资 · 李录': 'Value investing · Li Lu',
  '激进投资 · 纳尔逊·佩尔茨': 'Activist investing · Nelson Peltz',
  '对冲基金 · 戴维·艾因霍恩': 'Hedge fund · David Einhorn',
  '科技投资 · 布拉德·格斯特纳': 'Technology investing · Brad Gerstner',
  '人工智能投资 · 阿申布伦纳': 'AI investing · Aschenbrenner',
  '价值投资 · 乔尔·格林布拉特': 'Value investing · Joel Greenblatt',
  '成长投资 · 查克·阿克尔': 'Growth investing · Chuck Akre',
  '保险投资 · 汤姆·盖纳': 'Insurance investing · Tom Gayner',
  '质量投资 · 特里·史密斯': 'Quality investing · Terry Smith',
  '慈善信托 · 比尔·盖茨': 'Charitable trust · Bill Gates',
  '激进投资 · 克里斯托弗·霍恩': 'Activist investing · Christopher Hohn',
  '对冲基金 · 李·安斯利': 'Hedge fund · Lee Ainslie',
  '对冲基金 · 丹尼尔·桑德海姆': 'Hedge fund · Daniel Sundheim',
  '对冲基金 · 拉里·罗宾斯': 'Hedge fund · Larry Robbins',
  '对冲基金 · 博阿兹·温斯坦': 'Hedge fund · Boaz Weinstein',
  '主权基金 · 挪威': 'Sovereign wealth fund · Norway',
  '主权基金 · 新加坡': 'Sovereign wealth fund · Singapore',
  '公共养老金 · 加拿大': 'Public pension fund · Canada',
  '公共养老金 · 安大略教师': 'Public pension fund · Ontario teachers',
  '主权基金 · 沙特': 'Sovereign wealth fund · Saudi Arabia',
  '大学捐赠基金 · 哈佛': 'University endowment · Harvard',
  '主权基金 · 阿布扎比': 'Sovereign wealth fund · Abu Dhabi',
  '公共养老金 · 加州公务员': 'Public pension fund · California public employees',
  '公共养老金 · 加州教师': 'Public pension fund · California teachers',
  '公共养老金 · 魁北克': 'Public pension fund · Quebec',
  '量化对冲 · 克利夫·阿斯内斯': 'Quantitative hedge fund · Cliff Asness',
  '量化做市 · 纽约': 'Quantitative market making · New York',
  '自营交易 · 杰夫·亚斯': 'Proprietary trading · Jeff Yass',
  '多策略对冲 · 巴利亚斯尼': 'Multi-strategy hedge fund · Balyasny',
  '多策略对冲 · 迈克尔·格尔班德': 'Multi-strategy hedge fund · Michael Gelband',
  '公共养老金 · 安大略市政': 'Public pension fund · Ontario municipal employees',
  '量化对冲 · 伦敦': 'Quantitative hedge fund · London',
  '量化对冲 · 马歇尔与韦斯': 'Quantitative hedge fund · Marshall and Wace',
  '英伟达 创始人兼CEO': 'NVIDIA founder and CEO',
  '特斯拉 CEO': 'Tesla CEO',
  '亚马逊 创始人、执行董事长': 'Amazon founder and executive chair',
  '亚马逊 总裁兼CEO': 'Amazon president and CEO',
  'Meta 创始人兼CEO': 'Meta founder and CEO',
  '苹果 执行董事长': 'Apple executive chair',
  '微软 CEO': 'Microsoft CEO',
  'Alphabet CEO': 'Alphabet CEO',
  '谷歌 联合创始人、董事': 'Google co-founder and director',
  'AMD 董事长兼CEO': 'AMD chair and CEO',
  '博通 总裁兼CEO': 'Broadcom president and CEO',
  '甲骨文 创始人、董事长兼CTO': 'Oracle founder, chair and CTO',
  '甲骨文 执行副董事长': 'Oracle executive vice chair',
  '戴尔 创始人、董事长兼CEO': 'Dell founder, chair and CEO',
  '赛富时 董事长兼CEO': 'Salesforce chair and CEO',
  '帕兰提尔 CEO': 'Palantir CEO',
  '帕兰提尔 董事长': 'Palantir chair',
  '摩根大通 董事长兼CEO': 'JPMorgan Chase chair and CEO',
  '高盛 董事长兼CEO': 'Goldman Sachs chair and CEO',
  '贝莱德 董事长兼CEO': 'BlackRock chair and CEO',
  'Coinbase 创始人兼CEO': 'Coinbase founder and CEO',
  '奈飞 联合创始人': 'Netflix co-founder',
  '奈飞 联席CEO': 'Netflix co-CEO',
  '爱彼迎 创始人、董事长兼CEO': 'Airbnb founder, chair and CEO',
  '优步 CEO': 'Uber CEO',
  'Adobe 董事长兼CEO': 'Adobe chair and CEO',
  '通用汽车 董事长兼CEO': 'General Motors chair and CEO',
  '伯克希尔 荣誉董事长': 'Berkshire chair emeritus',
};

const STATES = {
  '俄亥俄': 'Ohio', '路易斯安那': 'Louisiana', '华盛顿州': 'Washington',
  '明尼苏达': 'Minnesota', '北卡': 'North Carolina', '佐治亚': 'Georgia',
  '加州': 'California', '马里兰': 'Maryland', '新泽西': 'New Jersey',
  '宾州': 'Pennsylvania', '肯塔基': 'Kentucky', '伊利诺伊': 'Illinois',
  '德州': 'Texas', '田纳西': 'Tennessee', '俄克拉荷马': 'Oklahoma',
  '南卡': 'South Carolina', '佛州': 'Florida', '弗吉尼亚': 'Virginia',
  '马萨诸塞': 'Massachusetts', '密歇根': 'Michigan', '威斯康星': 'Wisconsin',
};

export function englishRole(subject) {
  if (subject?.role_en) return subject.role_en;
  const role = subject?.r || '';
  if (ROLES[role]) return ROLES[role];
  const district = role.match(/^(前)?众议员 · (共和党|民主党) · (.+)第(\d+)选区$/);
  if (district && STATES[district[3]]) {
    return `${district[1] ? 'Former ' : ''}US House member · ${district[2] === '共和党' ? 'Republican' : 'Democrat'} · ${STATES[district[3]]} district ${district[4]}`;
  }
  return {ptr: 'Public official · House PTR', form4: 'Corporate insider · SEC Form 4', '13f': 'Institutional filer · SEC 13F'}[subject?.k] || '';
}
